# Generated by Django 5.0.6 on 2024-06-14 23:42

import cards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('game', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OnePieceGameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=200)),
                ('rotation', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('power', models.IntegerField()),
                ('effect', models.TextField()),
                ('traits', models.TextField()),
                ('type', models.CharField(choices=[('C', 'Character'), ('E', 'Event'), ('S', 'Stage')], max_length=1)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('UN', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super rare'), ('SEC', 'Secret'), ('TR', 'Treasure rare'), ('P', 'Promo')], max_length=5)),
                ('imagen', models.ImageField(null=True, upload_to=cards.models.img_path)),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.set')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
