# Generated by Django 5.0.6 on 2024-06-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseproduct')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('game', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
            ],
            bases=('inventory.baseproduct',),
        ),
        migrations.CreateModel(
            name='OnePieceGameCard',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.baseproduct')),
                ('code', models.CharField(max_length=10)),
                ('alternate_art', models.BooleanField(default=False)),
                ('rotation', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('power', models.IntegerField()),
                ('effect', models.TextField()),
                ('traits', models.TextField()),
                ('type', models.CharField(choices=[('C', 'Character'), ('E', 'Event'), ('S', 'Stage'), ('D', 'Don')], max_length=1)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('UN', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super rare'), ('SEC', 'Secret'), ('TR', 'Treasure rare'), ('P', 'Promo')], max_length=5, null=True)),
                ('card_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.set')),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.baseproduct',),
        ),
    ]
