# Generated by Django 5.0.6 on 2024-06-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepiecegamecard',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('UN', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super rare'), ('SEC', 'Secret'), ('TR', 'Treasure rare'), ('P', 'Promo')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='onepiecegamecard',
            name='type',
            field=models.CharField(choices=[('C', 'Character'), ('E', 'Event'), ('S', 'Stage'), ('D', 'Don')], max_length=1),
        ),
        migrations.AlterField(
            model_name='set',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
