# Generated by Django 5.0.6 on 2024-06-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_onepiecegamecard_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
